version: "2"
settings:
  conductor_base: centos:7
defaults:
  APP_NAME: blsearch
  APP_USER: "{{ APP_NAME }}"
services:
  main:
    from: centos:7
    roles:
      - blsearch
    ports:
      - "3000:3000"
      - "8983:8983"
    entrypoint: ["/usr/bin/dumb-init", "/bin/bash"]
    working_dir: "/var/www/{{ APP_NAME }}"
    user: "{{ APP_USER }}"
    dev_overrides:
      environment:
        - "DEBUG=1"
      command: ["/usr/bin/dumb-init", '/home/{{ APP_NAME }}/.rbenv/shims/foreman', 'start']
registries: {}
