---
- hosts: all
  remote_user: vagrant
  become: yes
  vars:
    app_user: vagrant
  tasks:
    - include: tasks/devtools.yml
    - include: tasks/nginx.yml
    - include: tasks/java.yml
    - include: tasks/maven.yml
    - include: tasks/nodejs.yml
    - include: tasks/ruby.yml
      become_user : "{{ app_user }}"
